setup ; % set a and harms: edit to alter
nl = {{'A4', 1, a, harms, level}, {'D5', 1, a, harms, level}, {'F#5', 1, a, harms, level},...
    {'A4', 1, a, harms, level}, {'D5', 1, a, harms, level}, {'F#5', 1, a, harms, level}, ...
    {'A4', 1, a, harms, level}, {'D5', 6, a, harms, level}} ; % put into a note list: edit to alter
s1 = create_tune(300, nl) ; % create the waveform: 1st param is beat rate
sound(s1, 44100) ; % play the waveform